/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/sample.glb -o ./src/Model.jsx 
*/

import React from "react";
import { MeshTransmissionMaterial, useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/sample.glb");
  return (
    <group scale={4} rotation={[1.3, 3.6, 0]} {...props} dispose={null}>
      <mesh geometry={nodes.geometry_0.geometry} castShadow receiveShadow>
        <MeshTransmissionMaterial
          color={"#007e2c"} // 재질의 색상
          backside={true} // 재질의 뒷면을 렌더링할지 여부
          thickness={0.3} // 재질의 두께
          roughness={0.3} // 재질의 거칠기
          transmission={0} // 빛의 투과율
          ior={1.5} // 굴절률 (Index of Refraction)
          chromaticAberration={0.3} // 색수차 (Chromatic Aberration)
          opacity={1}
          transparent={true} // 불투명도 적용을 위한 속성
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/sample.glb");
